import { Howl } from 'howler';
// Auto-generated manifest: prompt text → MP3 filename
// Generated by scripts/generate_speech.py using edge-tts
// Voice: en-US-AriaNeural, Rate: -5%, Pitch: +10Hz
import MANIFEST from './speech-manifest.json';

let enabled = true;
let voiceName: string | null = null;

const cache = new Map<string, Howl>();

const getFilename = (text: string): string | undefined => {
    if (text in MANIFEST) return (MANIFEST as Record<string, string>)[text];
    // Fallback: strip punctuation and try a fuzzy match
    const simple = text.toLowerCase().replace(/[^\w\s]/g, '').trim();
    for (const [key, filename] of Object.entries(MANIFEST as Record<string, string>)) {
        if (key.toLowerCase().replace(/[^\w\s]/g, '').trim() === simple) {
            return filename;
        }
    }
    return undefined;
};

const loadHowl = (filename: string): Howl => {
    const existing = cache.get(filename);
    if (existing) return existing;
    const howl = new Howl({
        src: [`/audio/speech/${filename}`],
        volume: 0.8,
        preload: true,
    });
    cache.set(filename, howl);
    return howl;
};

export const isSpeechSupported = (): boolean => true; // always supported with pre-recorded audio

export const listVoices = (): SpeechSynthesisVoice[] => []; // no longer relevant

export const setSpeechEnabled = (next: boolean): void => {
    enabled = next;
    if (!next) {
        // Stop any currently playing speech
        cache.forEach((howl) => howl.stop());
    }
};

export const setVoice = (_name: string | null): void => {
    // Voice is baked into the pre-recorded files — no-op for compatibility
};

export const speak = (text: string): void => {
    if (!enabled) return;

    const filename = getFilename(text);
    if (!filename) {
        // Fall back to browser TTS for any prompt not in the manifest
        if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
            window.speechSynthesis.cancel();
            const u = new SpeechSynthesisUtterance(text);
            const voices = window.speechSynthesis.getVoices().filter((v) => v.lang.startsWith('en'));
            const picked =
                voices.find((v) => v.name === voiceName) ??
                voices.find((v) => /samantha|aria|google us english/i.test(v.name)) ??
                voices[0];
            if (picked) u.voice = picked;
            u.rate = 0.95;
            u.pitch = 1.1;
            window.speechSynthesis.speak(u);
        }
        return;
    }

    // Stop any currently playing speech before starting a new one
    cache.forEach((howl) => howl.stop());

    try {
        loadHowl(filename).play();
    } catch {
        /* silent — autoplay block */
    }
};
