import type { SkillMeta } from '@/types/skill';

export const SKILLS: SkillMeta[] = [
    {
        id: 'count-to-10',
        name: 'Count to 10',
        description: 'Count things from 1 to 10!',
        ccStandard: 'K.CC.A.1',
        prereq: [],
        building: 'tent',
        position: { x: 22, y: 78 },
        order: 1,
    },
    {
        id: 'count-to-20',
        name: 'Count to 20',
        description: 'Count things from 1 to 20.',
        ccStandard: '1.NBT.A.1',
        prereq: ['count-to-10'],
        building: 'campfire',
        position: { x: 38, y: 62 },
        order: 2,
    },
    {
        id: 'recognize-0-20',
        name: 'Number Names 0–20',
        description: 'Read and recognize number symbols.',
        ccStandard: 'K.CC.A.3',
        prereq: ['count-to-10'],
        building: 'museum',
        position: { x: 55, y: 70 },
        order: 3,
    },
    {
        id: 'compare-numbers',
        name: 'Compare Numbers',
        description: 'Which is bigger? Use >, <, =.',
        ccStandard: '1.NBT.B.3',
        prereq: ['recognize-0-20'],
        building: 'bridge',
        position: { x: 68, y: 54 },
        order: 4,
    },
    {
        id: 'add-within-5',
        name: 'Add within 5',
        description: 'Easy addition up to 5.',
        ccStandard: '1.OA.C.6',
        prereq: ['recognize-0-20'],
        building: 'farm',
        position: { x: 45, y: 42 },
        order: 5,
    },
    {
        id: 'add-within-10',
        name: 'Add within 10',
        description: 'Addition up to 10.',
        ccStandard: '1.OA.C.6',
        prereq: ['add-within-5'],
        building: 'shop',
        position: { x: 62, y: 32 },
        order: 6,
    },
    {
        id: 'subtract-within-5',
        name: 'Subtract within 5',
        description: 'Easy subtraction up to 5.',
        ccStandard: '1.OA.C.6',
        prereq: ['add-within-5'],
        building: 'workshop',
        position: { x: 30, y: 30 },
        order: 7,
    },
    {
        id: 'subtract-within-10',
        name: 'Subtract within 10',
        description: 'Subtraction up to 10.',
        ccStandard: '1.OA.C.6',
        prereq: ['subtract-within-5', 'add-within-10'],
        building: 'cafe',
        position: { x: 48, y: 20 },
        order: 8,
    },
    {
        id: 'add-within-20',
        name: 'Add within 20',
        description: 'Addition up to 20.',
        ccStandard: '1.OA.C.6',
        prereq: ['add-within-10'],
        building: 'lighthouse',
        position: { x: 78, y: 22 },
        order: 9,
    },
    {
        id: 'subtract-within-20',
        name: 'Subtract within 20',
        description: 'Subtraction up to 20.',
        ccStandard: '1.OA.C.6',
        prereq: ['subtract-within-10'],
        building: 'observatory',
        position: { x: 60, y: 12 },
        order: 10,
    },
    {
        id: 'number-patterns',
        name: 'Number Patterns',
        description: 'Find the missing number!',
        ccStandard: '1.OA.D.8',
        prereq: ['count-to-20'],
        building: 'library',
        position: { x: 22, y: 50 },
        order: 11,
    },
    {
        id: 'place-value',
        name: 'Tens and Ones',
        description: 'Build numbers with tens and ones.',
        ccStandard: '1.NBT.B.2',
        prereq: ['count-to-20'],
        building: 'fountain',
        position: { x: 38, y: 12 },
        order: 12,
    },
];

export const skillById = (id: string): SkillMeta | undefined =>
    SKILLS.find((s) => s.id === id);
